export const loginCredentials = [
  { username: "Badda", password: "Badda@022" },
  { username: "Konapara", password: "Konapara@024" },
  { username: "Jatrabari", password: "Jatrabari@040" },
  { username: "Postogola", password: "Postogola@069" },
  { username: "Azampur", password: "Azampur@010" },
  { username: "Uttara", password: "Uttara@103" },
  { username: "Dakkhin khan", password: "Dakkhinkhan@063" },
  { username: "Fotullaone", password: "Fotullaone@016" },
  { username: "Fotulla-2", password: "Fotulla-2@073" },
  { username: "Panchaboti", password: "Panchaboti@057" },
  { username: "Lalbag", password: "Lalbag@044" },
  { username: "Dhanmondi", password: "Dhanmondi@020" },
  { username: "Shamoly", password: "Shamoly@053" },
  { username: "Noyabazarone", password: "Noyabazarone@012" },
  { username: "Noyabazar-2", password: "Noyabazar-2@125" },
  { username: "noyabazar090", password: "Noyabazar@090" },
  { username: "Armanitola", password: "Armanitola@014" },
  { username: "Sabuzbag", password: "Sabuzbag@026" },
];

// shamoli zone
// { username: "Badda", password: "Badda@022" },
// { username: "Konapara", password: "Konapara@024" },
// { username: "Sabuzbag", password: "Sabuzbag@026" },
// { username: "Jatrabari", password: "Jatrabari@040" },
// { username: "Postogola", password: "Postogola@069" },
// { username: "Azampur", password: "Azampur@010" },
// { username: "Uttara", password: "Uttara@103" },
// { username: "Dakkhin khan", password: "Dakkhinkhan@063" },
// { username: "Fotullaone", password: "Fotullaone@016" },
// { username: "Fotulla-2", password: "Fotulla-2@073" },
// { username: "Panchaboti", password: "Panchaboti@057" },
// { username: "Lalbag", password: "Lalbag@044" },
// { username: "Dhanmondi", password: "Dhanmondi@020" },
// { username: "Shamoly", password: "Shamoly@053" },
// { username: "Armanitola", password: "Armanitola@014" },
// { username: "Noyabazarone", password: "Noyabazarone@012" },
// { username: "Noyabazar-2", password: "Noyabazar-2@125" },
// { username: "noyabazar090", password: "Noyabazar@090" },
