export const loginCredentials = [
  { username: "fotulla-1", password: "12345678" },
  { username: "badda", password: "badda022" },
  { username: "jatrabari040", password: "jatrabari040" },
  { username: "postogola123", password: "postogola123" },
  { username: "konapara", password: "konapara" },
  { username: "nayabazar1", password: "nayabazar1" },
  { username: "noyabazar2", password: "noyabazar2" },
  { username: "noyabazar3", password: "noyabazar3" },
  { username: "Nayabazar-2", password: "Nayabazar-2" },
  { username: "sabuzbag", password: "sabuzbag" },
  { username: "azampur", password: "01877703010PmK" },
  { username: "dkhan063", password: "dkhan063" },
  { username: "uttara103", password: "103Uttara2585@" },
  { username: "panchaboti", password: "panchaboti" },
  { username: "fotulla-2", password: "fotulla-2" },
  { username: "samoli", password: "053$Samoli" },
  { username: "lalbag", password: "lalbag044" },
  { username: "dhanmondi", password: "dhanmondi020" },
];
